version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
        prefix: "chore"
        include: "github-actions"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
        prefix: "chore"
        include: "cargo"
    groups:
      all:
        patterns:
          - "*"
