name: Setup Environment
inputs:
  CACHIX_AUTH_TOKEN:
    required: true
    description: 'Cachix Auth Token'
runs:
  using: "composite"
  steps:

    - name: Installing Nix
      uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - uses: cachix/cachix-action@v12
      with:
        name: nixos-metrics
        authToken: '${{ inputs.CACHIX_AUTH_TOKEN }}'
