name: "CI for website"

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
  push:
    branches:
    - website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checking out the repository
      uses: actions/checkout@v3
      with:
        ref: website


    - name: Setup
      uses: ./.github/actions/nix-common-setup
      with:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Flake check
      run: |
        nix flake check
