name: "Daily website"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
  - cron: '0 4 * * *' # runs daily at 04:00, right after the `data` branch is updated

jobs:

  process:
    runs-on: ubuntu-latest
    steps:

    - name: Checking out main branch
      uses: actions/checkout@v3
      with:
        path: data

    - name: Checking out the website branch
      uses: actions/checkout@v3
      with:
        path: website
        ref: website

    - name: Setup
      uses: ./main/.github/actions/nix-common-setup
      with:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Process scraped data
      run: |
        nix run ./website > website/data.json

    - name: Commit processed data to website branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Daily generation of website graph
        repository: ./website
        branch: website
        file_pattern: data.json
        commit_user_name: NixOS webmaster
        commit_user_email: webmaster@nixos.org
        commit_author: GitHub Actions <webmaster@nixos.org>
      if: github.repository == 'NixOS/nixos-metrics'
